services:
  - type: web
    name: aljawhara-lmm
    env: python
    plan: free

    buildCommand: ""
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000

    envVars:
      - key: GITHUB_TOKEN
        sync: false
      - key: GITHUB_USERNAME
        sync: false
